<a href="https://colab.research.google.com/github/AlfanMarcel/MachineLearning/blob/main/Jobsheet9_Tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Praktikum

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

### Langkah 1 - Import Library

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Langkah 2 - Pra-pengolahan data MNIST

In [2]:
# Pra-pengolahan data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data() # load data MNIST dan split data

# ubah bentuk fitur menjadi vektor dan dinormalisasi
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

11490434/11490434 [==============================] - 0s 0us/step


### Langkkah 3 - Buat Arsitektur ANN

In [3]:
# Arsitektur ANN
# Terdiri dari 3 lapisan Dense dengan funsi aktivasi ReLU
ann = keras.Sequential(
    [
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(10),
    ]
)


### Langkah 4 - Buat Fugsi Aktivasi

In [4]:
# Fungsi aktivasi
ann.compile(
    optimizer=keras.optimizers.Adam(0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

### Langkah 5 - Latih Model ANN dan Lakukan Evaluasi Model

In [5]:
# Pelatihan model
# Model dilatih menggunakan data latih dengan batch size 32 dan epoch sebanyak 5 kali.
ann.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

# Evaluasi model
# Model dievaluasi menggunakan data uji dan menghitung akurasi.
test_loss, test_acc = ann.evaluate(x_test, y_test, verbose=2)
print("Test accuracy:", test_acc)

Epoch 1/5
1875/1875 - 11s - loss: 0.2054 - accuracy: 0.9384 - 11s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 9s - loss: 0.0871 - accuracy: 0.9728 - 9s/epoch - 5ms/step
Epoch 3/5
1875/1875 - 8s - loss: 0.0579 - accuracy: 0.9816 - 8s/epoch - 4ms/step
Epoch 4/5
1875/1875 - 9s - loss: 0.0450 - accuracy: 0.9855 - 9s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 9s - loss: 0.0356 - accuracy: 0.9882 - 9s/epoch - 5ms/step
313/313 - 1s - loss: 0.0720 - accuracy: 0.9793 - 797ms/epoch - 3ms/step
Test accuracy: 0.9793000221252441


### Langkah 6 - Tampilkan Confusion Matrix

In [6]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = ann.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 1s 2ms/step
Confusion matrix:
 tf.Tensor(
[[ 970    1    0    1    0    1    4    2    1    0]
 [   0 1129    0    2    0    0    1    0    3    0]
 [   4    4 1004    3    2    0    2   10    3    0]
 [   0    0    5  986    0    9    0    4    5    1]
 [   2    1    4    0  963    0    5    2    0    5]
 [   2    0    0    6    1  874    3    1    4    1]
 [   2    2    0    1    5    2  945    0    1    0]
 [   0    7    8    1    2    0    0 1007    2    1]
 [   4    1    4    6    3    1    1    4  948    2]
 [   1    5    0    7   10    7    0    7    5  967]], shape=(10, 10), dtype=int32)
